### ISSUE TITLE
DpDatePickerModule is not an NgModule

### ISSUE THREAD

**Issue by codedoge** [vlio20/ng2-date-picker#8]
I'm getting the error
`DpDatePickerModule is not an NgModule`
in a angular-cli based application. I downloaded and imported the module as said in the guide.

**Comment by vlio20** [comment]
Can you create some repo so I can check?

**Comment by vlio20** [comment]
@codedoge , this issue was fixed in v0.2.1 

Thanks for the issue.

**Comment by codedoge** [comment]
I'm still getting this error with angular-cli 1.0.0-beta.24 and ng2-date-picker 0.2.1. I'm also using typescript 2.1.4 (don't know if this is related).
Do you have an idea of what could be the problem or area related to this. Could it be a problem with my project configuration?

**Comment by codedoge** [comment]
I tried importing the module in a new angular cli project (ver 1.0.0-beta.24) and it doesn't work even in this case. I also tried upgrading all @angular/* packages  to the latest version with no luck.

**Comment by vlio20** [comment]
@codedoge , it would be great if you will create some simple project and publish it on github. Can you do it?

**Comment by codedoge** [comment]
you can find it here https://github.com/codedoge/datepicker-issue.
I usually "npm install --save {package-name}" to install packages.

**Comment by vlio20** [comment]
Looking into it, will update ASAP

**Comment by vlio20** [comment]
@codedoge, seems like there is an issue with the new versions of angular cli: https://github.com/gulpjs/gulp/issues/259. However I plan to move my module to be built and developed on pure homemade configuration.

**Comment by codedoge** [comment]
Yes, I noticed later that this is also happening to other projects and it probably depends on angular-cli. Thanks for the support

**Comment by vlio20** [comment]
@codedoge , see this SO: http://stackoverflow.com/a/41424263/1691423

**Comment by samrantmedia** [comment]
I am getting this issue with typescript version 2.2.1, I am not keen to make my project depend on an old version of typescript

**Comment by vlio20** [comment]
are you sure thi

**Comment by Grapadacious** [comment]
@vlio20, check out <a href="https://github.com/angular/angular-cli/issues/3426#issuecomment-269673735">this comment</a> over on the Angular CLI project. I think it might help you solve this issue. Keep up the good work. This is the best Angular 2 datepicker I've found.

**Comment by vlio20** [comment]
@Grapadacious, thanks!  
I will check it out - though I tired it previously.

@samrantmedia, I have updated to the latest cli version. Please see if it helps.

**Comment by samrantmedia** [comment]
I'm not sure if it is a typescript issue. I'm using angular-cli 1.0.0-beta-21 and it is working fine. It was working on 1.0.0-beta.28.3. I was able to run the app on that version, by commenting it out, waiting for it to  start up and then commenting it back in again. However, doing a build would not work. This older version of the cli is noticably slower to compile and less elegant to use, so I am looking forward to a fix. Still, thanks for the hard work on the date-picker it works really well.

**Comment by vlio20** [comment]
@samrantmedia, let me know if you will find a solution for that issue.

**Comment by pieterlouw1974** [comment]
Try editing the file picker.module.d.ts to this

import { NgModule } from '@angular/core';
@NgModule({
	declarations: [
		DateTimePickerModule
	]
})
export declare class DateTimePickerModule {
}

**Comment by vlio20** [comment]
@pieterlouw1974, you mean that I only should add the declare statement?

**Comment by vlio20** [comment]
@pieterlouw1974, adding declare didn't help.

**Comment by vlio20** [comment]
@isaacplmann, I saw you are blogging about lib creation for ng2. Maybe you can assist with this one?

**Comment by isaacplmann** [comment]
I have run into this with other libraries too and I can reproduce it when using your lib in my app.  Another work around is simply to save any file to force webpack to rebuild - any build after the first one doesn't cause the error.

One way I fixed this error is by changing @angular dependencies to peerDependencies - but you don't have `@angular` in your dependencies.  You could try moving moment to peerDependencies, but I don't see why that would cause this problem.

**Comment by isaacplmann** [comment]
I'll take a look at this issue when I have time.  I'll need to fix this before I use the library in my app anyway, and I do plan to use it.

**Comment by vlio20** [comment]
@isaacplmann, I think it is related to the metadata.json and AOT. I currently struggling running ngc because I am using less. Any suggestions on how to make ngc work with less would be welcome.

**Comment by samrantmedia** [comment]
@isaacplmann i was doing the same workaround in dev. The workaround, unfortunately, does not work when you want to run: 'ng build'

**Comment by vlio20** [comment]
The issue was fixed! it is currently in the master branch will release it as part of the v1 version! @isaacplmann, thanks for the help!!!

**Comment by samrantmedia** [comment]
Great! Looking forward to using this. Is there a rough estimate for this release date?

**Comment by vlio20** [comment]
@samrantmedia, there are still some tasks I want to do before that. I believe it will  be ready in the next couple of weeks.

**Comment by samrantmedia** [comment]
@vlio20 great, thanks for letting me know a rough estimate. I'm looking forward to using v1 when it's ready

**Comment by kamlekar** [comment]
Hi @vlio20,

Greate useful pIugin,

I am still getting this error now. `DpDatePickerModule is not an NgModule` in version `2.7.2`

**Comment by vlio20** [comment]
please follow this thread #336
